name: Morebits integration tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install system dependencies for browsers
        uses: microsoft/playwright-github-action@v1
      - run: Install npm dependencies
      - name: Setup MediaWiki instance using Docker
        run: npm run test:integration:setup
      - name: Run integration tests
        run: npm run test:integration
