name: Morebits function tests

on:
  push:
    paths:
    - 'morebits.js'
    - 'tests/**'
  pull_request:
    paths:
    - 'morebits.js'
    - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Morebits tests
      run: npm run test
